trigger:
  branches:
    include:
      - '*'

pool:
  name: 'Azure Pipelines'
  vmImage: 'ubuntu-22.04'

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '17'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'spring-boot:build-image'
