trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

container: maven:3.8.5-openjdk-17-slim

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx1024m'
      javaHomeOption: 'path'
      jdkDirectory: '/usr/local/openjdk-17'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'spring-boot:build-image'