trigger:
  branches:
    include:
      - '*'

pool:
  name: 'Azure Pipelines'
  vmImage: 'ubuntu-22.04'

steps:

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        chmod +x mvnw # https://github.com/pascalgrimaud/generator-jhipster-docker/issues/29
        echo 'Build docker image with Maven wrapper'
        ./mvnw spring-boot:build-image
